version: "3.9"
services:

  # mongodb services
  #  mongo_db:
  #    container_name: mongo_container
  #    image: mongo:latest
  #    restart: always
  #    ports:
  #      - 27018:27017
  #    volumes:
  #      - /app/mongo_db:/data/db
  #

#  user-services:
#    build: ./users
#    restart: always
#    command: nodemon -L src/server.js
#    ports:
#      - 2003:2003
#    volumes:
#      - ./users:/app/users
#    env_file:
#      - ./users/.env
##    depends_on:
##      - rabbitmq

#
#  products_services:
#    build: ./products
#    restart: always
#    command: nodemon -L src/server.js
#    ports:
#      - 2010:2010
#    volumes:
#      - ./products:/app/products
#    env_file:
#      - ./products/.env



  orders_services:
    build: orders
    restart: on-failure
    command: nodemon -L src/server.js
    ports:
      - 2013:2013
    volumes:
      - ./orders:/app/orders
    env_file:
      - orders/.env


#  cart_services:
#    build: carts
#    restart: always
#    command: nodemon -L src/server.js
#    ports:
#      - 2014:2014
#    volumes:
#      - ./carts:/app/carts
#    env_file:
#      - carts/.env
##    depends_on:
##      - rabbitmq
