version: "3.9"
services:

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"


#  nginx:
#    image: nginx
#    ports:
#      - "80:80"
#    container_name: my_nginx
